import { test } from '@playwright/test';
import { HomePage } from '../pages/HomePage';


test('Reservation rome napoli mastene manel', async ({ page }) => {
  const homePage = new HomePage(page);

  await homePage.ouvrir();

  await homePage.accepterCookies();

  await homePage.destinations();

  await homePage.saisirDestination('rome');
  
  await page.locator('#bs-select-1-318').click();
  await page.locator('button').filter({ hasText: 'Ville de départ' }).click();
  await page.getByRole('combobox', { name: 'Search' }).fill('ni');
  await page.getByRole('combobox', { name: 'Search' }).press('Enter');
  await page.getByRole('textbox', { name: 'JJ/MM/AAAA' }).click();
  await page.getByRole('button', { name: 'Mois prochain' }).click();
  await page.getByRole('button', { name: '18' }).nth(1).click();
  await page.locator('button').filter({ hasText: 'Type de voyage' }).click();
  await page.getByRole('option', { name: '   Hôtels' }).click();
  await page.locator('button').filter({ hasText: 'Durée du séjour' }).click();
  await page.locator('#bs-select-4-1').click();
  await page.getByTestId('searchSubmit').click();
  await page.getByRole('textbox', { name: 'JJ/MM/AAAA' }).click();
  await page.getByRole('button', { name: 'Mois prochain' }).click();
  await page.getByRole('button', { name: '7' }).nth(3).click();
  await page.getByTestId('searchSubmit').click();
  await page.getByRole('combobox', { name: 'Munich' }).click();
  await page.getByRole('combobox', { name: 'Search' }).fill('paris');
  await page.locator('#bs-select-2-8').click();
  await page.getByTestId('searchSubmit').click();
  await page.getByRole('checkbox', { name: 'Naples' }).check();
  await page.getByText('4 * Sup').click();
  await page.getByRole('checkbox', { name: '* Sup' }).uncheck();
  await page.getByRole('checkbox', { name: '3 * Sup' }).check();
  await page.getByRole('checkbox', { name: '* Sup' }).uncheck();
  await page.getByRole('checkbox', { name: 'Été' }).check();
  await page.getByRole('checkbox', { name: 'Été' }).uncheck();
  await page.getByRole('checkbox', { name: 'Petit Déjeuner' }).check();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Découvrir' }).click();
  const page1 = await page1Promise;
  await page1.locator('#image_1').click();
  await page1.getByRole('button', { name: 'Next slide' }).click();
  await page1.getByRole('button', { name: 'Next slide' }).click();
  await page1.getByRole('button', { name: 'Next slide' }).click();
  await page1.getByRole('button', { name: 'Next slide' }).click();
  await page1.getByRole('button', { name: 'Next slide' }).click();
  await page1.getByRole('button', { name: 'Close gallery' }).click();
  await page1.getByText('Situé juste à côté de la').click();
  await page1.getByTestId('calendar').getByTestId('price-min').click();
  await page1.getByTestId('child_number_more').click();
  await page1.getByTestId('child_number_less').click();
  await page1.getByTestId('productToResaButton').click();
  await page1.goto('https://booking.jettours.com/q/1639eb34-1832-45cc-bc2e-c9b8ef18fcfc');
  await page1.getByText('Voir plus de vols').click();
  await page1.getByText('Choisir').nth(2).click();
  await page1.locator('#flightLuggagePopup_1').getByText('Oui, je le souhaite').click();
  await page1.getByRole('checkbox').first().check();
  await page1.getByRole('button', { name: 'Valider' }).click();
  await page1.getByRole('button', { name: 'Continuer >' }).click();
  await page1.locator('#contact-info-left-column').getByRole('combobox').selectOption('Mr');
  await page1.locator('#contact-info-left-column').getByRole('textbox', { name: 'Prénom' }).click();
  await page1.locator('#contact-info-left-column').getByRole('textbox', { name: 'Prénom' }).fill('Mastene');
  await page1.locator('#contact-info-left-column').getByRole('textbox', { name: 'Prénom' }).press('Tab');
  await page1.locator('#contact-info-left-column').getByRole('textbox', { name: 'Nom', exact: true }).fill('Messouya');
  await page1.locator('#contact-info-left-column').getByRole('textbox', { name: 'Nom', exact: true }).press('Tab');
  await page1.getByRole('textbox', { name: 'Téléphone 1' }).fill('0767396842');
  await page1.getByRole('textbox', { name: 'Téléphone 1' }).press('Tab');
  await page1.getByRole('textbox', { name: 'Téléphone 2 (facultatif)' }).press('Tab');
  await page1.getByRole('textbox', { name: 'Email', exact: true }).fill('messouyamastene@outlook.com');
  await page1.getByRole('textbox', { name: 'Email', exact: true }).press('Tab');
  await page1.getByRole('textbox', { name: 'Confirmer email' }).fill('messouyamastene@outlook.com');
  await page1.getByText('Je participe au voyage Pays').click();
  await page1.getByRole('textbox', { name: 'Adresse' }).click();
  await page1.getByRole('textbox', { name: 'Adresse' }).fill('01 Allee paul Eluard');
  await page1.getByRole('textbox', { name: 'Adresse' }).press('Tab');
  await page1.getByRole('textbox', { name: 'Ville' }).fill('Colombes');
  await page1.getByRole('textbox', { name: 'Ville' }).press('Tab');
  await page1.getByRole('textbox', { name: 'Code postal' }).fill('92700');
  await page1.getByRole('textbox', { name: 'Code postal' }).press('Tab');
  await page1.locator('#contact-info-right-column').getByRole('combobox').selectOption('FR');
  await page1.getByRole('combobox').nth(3).selectOption('Mrs');
  await page1.getByRole('textbox', { name: 'Prénom' }).nth(2).click();
  await page1.getByRole('textbox', { name: 'Prénom' }).nth(2).fill('Manel');
  await page1.getByRole('textbox', { name: 'Prénom' }).nth(2).press('Tab');
  await page1.getByRole('textbox', { name: 'Nom' }).nth(5).fill('Guemmat');
  await page1.getByRole('textbox', { name: 'jj/mm/aaaa' }).nth(1).click();
  await page1.getByRole('textbox', { name: 'jj/mm/aaaa' }).first().click();
  await page1.locator('section').click();
  await page1.getByText('Assurance Multirisque Flex').click();
});